### ISSUE TITLE
Excel Version

### ISSUE THREAD

**Issue by rumirocz** [rathergood/Crypto-Currency-Price#11]
Not an issue. Thanks for creating this, I'm using it on a Google Sheet. Had to make an Excel version for a friend and started using that too. If you want it, the code is here: https://github.com/rumirocz/Excel-Cypto-Portfolio

Thanks for showing me this was possible. It didn't even cross my mind until I saw your version.

**Comment by rathergood** [comment]
No prob fellow "human"
