### ISSUE TITLE
Coinmarketcap change

### ISSUE THREAD

**Issue by zdavis28** [rathergood/Crypto-Currency-Price#12]
CMC limited the API and this now fails if you have more than 30 function calls in a minute.

**Comment by rathergood** [comment]
thank you for opening this issue. I am currently working to integrate api v2 into the code. Not quite sure what i'm going to do about the new cap- if anyone has any suggestions of how to decrease the number of calls. Perhaps call everything at once, and then parse in google scripts?

**Comment by tmlee** [comment]
Hey, I would like to suggest considering our API endpoints https://www.coingecko.com/api/docs/v3 from https://www.coingecko.com/en

There are a couple of known services that have deployed our API in production

Our rate limit is quite flexible as we aim towards simplicity of API consumption
For this use case, may I suggest the /coins/markets endpoint with no pagination
eg. https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd

Would like to hear your thoughts on that

**Comment by rathergood** [comment]
I tried updating the code for the new CMC pro API, but it still throws the same error after more than 30 calls in a minute. Seems CMC is now solely focused on $$$$$$

If anyone wants the updated code, send me a message. Doesn't really seem worth updating the repo with it erroring out so easy with the free tier (it's also a pain to set up now, not nearly as user friendly as the old one was)

@tmlee i'll check out the coingecko endpoints next time I get some freetime

**Comment by theMikeD** [comment]
```
//returns price (or other info) of cryptocurrency from coingecko api.
//takes two parameters, the name of the cryptocurrency and info that you want returned about the cc

//example: =ccprice("ethereum", "USD")

function ccprice(name, currency) {
  var url = "https://api.coingecko.com/api/v3/simple/price?ids=" + name + "&vs_currencies=" + currency
  var response = UrlFetchApp.fetch(url);
  var json = response.getContentText();
  var data = JSON.parse(json);

  var priceval = data[name][currency];
  var price = parseFloat(priceval)
  return price
}
```

**Comment by rathergood** [comment]
I've updated the code so that it now uses the coingecko api. thanks for the input everyone.
@tmlee

**Comment by 2smpl2** [comment]
@rathergood I've noticed it's working better. Thank you very much!

**Comment by tmlee** [comment]
awesome! thats really good to hear
