### ISSUE TITLE
golem and heat 

### ISSUE THREAD

**Issue by jeevesj** [rathergood/Crypto-Currency-Price#2]
Everything worked awesome,

except for two of the coins I am trying to track. Golem and HEAT. Do you know how i can get live prices for them as well??

Thanks, I don't have very great working knowledge of coding.

**Comment by rathergood** [comment]
for golem use "golem-network-tokens" and heat use "heat-ledger"
if a cc doesn't work, find it on coinmarketcap and then use the name of the cc in the website address.
for example:
https://coinmarketcap.com/currencies/heat-ledger/
