### ISSUE TITLE
Request failed - Script editor

### ISSUE THREAD

**Issue by polbrigneti** [rathergood/Crypto-Currency-Price#7]
Hi there,

Although the formula works on the spreadsheet when I run the javascript code I keep getting the same error message:

Request failed for https://api.coinmarketcap.com/v1/ticker/undefined?convert=undefined returned code 404. 

And this code gets highlighted: var response = UrlFetchApp.fetch(url);

Thank you

**Comment by rathergood** [comment]
This is a function that needs parameters passed to it (via the spreadsheet), not a standalone script. When you run the script itself, there are no defined parameters, and you are asking coinmarketcap for data from a website that doesn't exist ("undefined" ticker).

For what purpose are you trying to run the code?

**Comment by polbrigneti** [comment]
Is there a way to set a trigger then? or it won't work because the url doesn't exists since the parameters are missing?

Just curious.

Thanks

**Comment by rathergood** [comment]
i'm not quite sure what you mean by trigger.

This isn't javascript, it's Google Apps script, which is based on JS, but not meant to be run outside of the context of google apps...

**Comment by polbrigneti** [comment]
On the google script editor you can find a clock logo which is used to set project triggers. You can schedule when do you want the script to be run to update the data.

Anyway it doesn't work because the url set on the script doesn't exist.
